name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22, 24, 26]
    name: Node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: sudo apt-get install -y redis-server
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm test
